### ISSUE TITLE
Avoiding rails 4.2.1+??

### ISSUE THREAD

**Issue by nov** [TwoFactorAuth/ruby#4]
The `activemodel` version restriction in your gemspec rejecting rails 4.2.1+.
Is it intentional?

**Comment by pushcx** [comment]
I'm paranoid about minor changes in Rails breaking something it relies on, so I cap the version until I've had a chance to test. Bumping now.

**Comment by olemd** [comment]
With ruby 2.2.3 and rails 4.2.4 this doesn't work. The dependency on activemodel 4.2 refuses to allow activemodel 4.2.4.
