### ISSUE TITLE
Rails 5 Compatibility

### ISSUE THREAD

**Issue by roolo** [TwoFactorAuth/ruby#9]
It looks like from rubygems dependency POV, TwoFactorAuth is not compatible with Rails 5. Is there some WIP for Rails 5?

~~~shell
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 5.0.0.1)

  In Gemfile:
    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
      activemodel (= 5.0.0.1)

    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
      activemodel (= 5.0.0.1)

    two_factor_auth was resolved to 0.1.1, which depends on
      activemodel (<= 4.2, ~> 4.0)

    web-console was resolved to 3.4.0, which depends on
      activemodel (>= 5.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
~~~

**Comment by pushcx** [comment]
It's not currently compatible with Rails 5 and there are no plans to make it so.

The U2F standard has [failed to get much adoption](http://caniuse.com/u2f) (though there is a Firefox extension now, at least). I haven't been able to sell any commercial licenses, so I haven't had any incentive to upgrade the project.

When there's commercial interest, I'll do it in a heartbeat.
